{
 "title": "Gitlab job monitoring",
 "description": "Info cpu, mem, network about gitlab job",
 "tags": [
  "gitlab-runner",
  "job"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels,namespace)"
    }
   },
   {
    "name": "label_job_name",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\"},label_job_name)"
    }
   },
   {
    "name": "label_project_name",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_job_name=~\"$label_job_name\"},label_project_name)"
    }
   },
   {
    "name": "label_pipeline_id",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_job_name=~\"$label_job_name\", label_project_name=~\"$label_project_name\"},label_pipeline_id)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_job_name=~\"$label_job_name\", label_project_name=~\"$label_project_name\", label_pipeline_id=~\"$label_pipeline_id\"},pod)"
    }
   },
   {
    "name": "label_pipeline_id_pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$namespace\", label_job_name=~\"$label_job_name\", label_project_name=~\"$label_project_name\", pod=~\"$pod\"},label_pipeline_id_pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total App Resources",
   "type": "table",
   "description": "Сводная таблица по ресурсам подов",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$pod\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{pod=~\"$pod\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\"}) by (pod) *100"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\"}) by (pod) * 100"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory Requests usage by pod",
   "type": "timeseries",
   "description": "Использование memory requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"$pod\", resource=\"memory\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory  Limits by pod",
   "type": "timeseries",
   "description": "Использование memory лимитов ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"$pod\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Requests usage by pod",
   "type": "timeseries",
   "description": "Использование CPU requests ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"$pod\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU  Limits by pod",
   "type": "timeseries",
   "description": "Использование CPU лимитов",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"$pod\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage by pod",
   "type": "timeseries",
   "description": "Потребление процессорного времени",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage by pod",
   "type": "timeseries",
   "description": "Потребление памяти",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Throttle",
   "type": "timeseries",
   "description": "Троттлинг CPU",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=~\"$pod\",image!=\"\"}[5m])) by (pod) /sum(increase(container_cpu_cfs_periods_total{pod=~\"$pod\",image!=\"\"}[5m])) by (pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": " {{pod}} Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{ pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  },
  {
   "title": "Network - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  }
 ]
}