tolerations:
  - operator: Exists
    effect: NoSchedule
config:
  clients:
    - url: http://victorialogs-victoria-logs-single-server.victorialogs.svc.cluster.local:9428/insert/loki/api/v1/push?_msg_field=msg
  snippets:
    pipelineStages:
      - cri: {}
      - labeldrop:
          - filename
          - node_name
    extraRelabelConfigs:
      - action: keep
        source_labels:
          - __meta_kubernetes_namespace
        regex: gitlab-runner
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_job_id
        target_label: job_id
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_job_name
        target_label: job_name
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_pipeline_id
        target_label: pipeline_id
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_project_id
        target_label: project_id
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_project_name
        target_label: project_name
