grafana:
  plugins:
    - victoriametrics-metrics-datasource
    - victoriametrics-logs-datasource
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - grafana.apatsev.org.ru
kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[*]
